### ISSUE TITLE
End the damn tumbling, insert interactive porno

### ISSUE THREAD

**Issue by zijistark** [zijistark/EMF#10]
Kill the vanilla "tumbling" event. It's old. It's repetitive. It lacks any positive RP characteristics.

Instead, sow your wild oats in stages.  Using the interactive-immediate approach to character interaction, perhaps you happen to flirt with the girl/boy around court once or twice, with history to remember the relationship.  This could be achieved from feast hooks, generally any social hook, random event whenever you're actually home at court, etc.

During stage 1, almost always give the player an exit strategy.  It's debatable whether particularly lustful characters should be forced to act lustfully, but I tend to think the player should RP as they please.  Maybe it's humorous or cruel or simply a 'Not Interested,' but the player should no longer receive flirtatious events from that character if they take the exit strategy (unless they're some *other* kind of events about fat chicks / horny suitors that *just won't go away*). Likewise, the AI should spurn the player sometimes.

During stage 2, a "special relationship" of sorts has been established.  It may be quite awhile before another event happens when stage 2 is engaged after establishing an "interest" relationship, and it should be able to happen in multiple ways.  The player and the other character both have an inkling there is mutual fondness, even if one of the characters won't act upon it.  A "special meeting" might happen where one of the options of the dialogue (or as it comes up to the player) is to spend that one night together (proceeding directly to stage 3), give her / receive a poem, hold hands walking in the moonlight, whatever.  If each of the characters proceeds past this, we get to...

Stage 3. Ker-blam.  You've just fucked your son's wife.  Or your sister (yes, open up the incest taboos completely-- people eat them up, for good reason).  Or, if single, you've maybe proposed to her after one all-night affair.  Or you've simply engaged in playboy for the night, and it's back to business (most of the time).  Here "lover" status may or may not be achieved, depending upon how you choose / things chose to leave the encounter.

Damn the the tumbling.

**Comment by thefinestsieve** [comment]
Because this has been more or less covered by Way of Life features, I'm closing this.
