### ISSUE TITLE
Special flavor for sacrificing a foreign religious head at a Blot

### ISSUE THREAD

**Issue by zijistark** [zijistark/EMF#121]
From the EMF thread (@Jorlem):

> This is rather minor, compared to everything else described, but could I request a unique event (or a set of similar unique events) for when I sacrifice a foreign religious head at a blot? When I sacrifice the Pope, the event shouldn't be exactly the same as when I sacrifice some random Catholic courtier, you know?

Not our highest priority right now but also relatively easy to address and a perfect fit within the charter of the F in EMF.  Whenever somebody feels like writing some *WE JUST SACRIFICED THEIR FRICKIN' MAN-THOR* flavor... Probably results in a huge opinion malus from the independent leaders of the Catholic world, not that such would trouble the Norse, and a chance at the ````zealous```` trait.

Do other pagan event chains sacrifice religious characters?

**Comment by thefinestsieve** [comment]
Oddly enough, I saw a [post on reddit] (http://www.reddit.com/r/CrusaderKings/comments/2y0u70/sacrificing_the_popeshame_it_doesnt_give_more/) about sacrificing the Pope and it reminded me that we have this issue. I think we should do it. 

For minimal impact, we wouldn't even necessarily need to modify any sacrifice event chain. Instead, we could create a followup on_death on_action narrative event tied to the religious title in question (k_papal_state and whatever others we might want special flavor for) and have it create the appropriate opinion changes, plus flavor, piety, prestige, chance at traits, etc for the character who sacrificed the religious leader. This way, we'd compatible with all sacrifice chains. And because we can dynamically change event and option text, we could easily customize the flavor based the religions involved.

**Comment by Jorlem** [comment]
As a heads up, [Groogy has said] (http://forum.paradoxplaza.com/forum/showthread.php?776969-The-Legacy-of-the-Vogelius-Dynasty-The-Rising-Raven&p=18817528&viewfull=1#post18817528) that he's planning on trying to get a bit of extra flavor for this situation added to the game.

**Comment by zijistark** [comment]
@Jorlem Thanks.

@thefinestsieve (Anax) Sadly, I don't think we can do this as an on_death on_action. It's a great idea, but the death reason is most definitely not available in that event (because the character's not dead yet). That said, how many sacrifice event chains are there?

**Comment by zijistark** [comment]
@thefinestsieve Workaround that might make your idea work: on_death event schedules a bounce event to Isis/e_hip for the next day for such characters. Isis then check's FROM's death_reason and issues a narrative event if it was a sacrifice (or, I suppose, other interesting ways to die).

**Comment by zijistark** [comment]
So, really, the topic of this Issue shifts to: global narrative events upon the [various interesting forms of] untimely death of religious leaders (or other interesting characters-- perhaps any emperors).

Interesting:
- death_sacrifice
- death_battle
- death_duel
- death_murder (known), maybe?

Perhaps some of those narrative events' delivery would be limited by distance.

**Comment by thefinestsieve** [comment]
I've implemented the basic framework for doing this and confirmed it works. First up, I'm going to be adding flavor and small mechanics for a Pope who gets sacrificed. This is what I'm thinking:
* The character who sacrificed the Pope gets bonus prestige and piety (and eventually a trait)
* All Catholics (probably limited to rulers and their heirs?) hate the Pope's killer for life
* Catholic MA takes a big hit, while the religion of the killer gets a nice MA bump
* The new Pope becomes a rival of the killer

Any other suggestions are welcome, especially in the vein of specific flavor or mechanics

**Comment by zijistark** [comment]
> - All Catholics (probably limited to rulers and their heirs?) hate the Pope's killer for life
Limit it to playable rulers (count-tier and above), and make the opinion modifier ````inherit = yes```` and last for 50 years or whatever. It's mostly just for flavor since a Norsemen could give a shit if everybody and their vassals hates them, but it's always nice seeing all red on the Catholic sections of the opinion map mode.

> - Catholic MA takes a big hit, while the religion of the killer gets a nice MA bump
Not too hard on MA. It's not like it really has any major effect on the moral authority of a religion. Some might even argue that the opposite response would make sense, so I'd say small MA changes.

**Comment by thefinestsieve** [comment]
> Not too hard on MA. It's not like it really has any major effect on the moral authority of a religion. Some might even argue that the opposite response would make sense, so I'd say small MA changes.

I do think that's a little debatable. At the very least it seems like it would shake the faith of many folks when they hear God's representative on Earth has been taken and sacrificed to heathen gods. But regardless right now I'm thinking roughly a 10 point MA change for each religion involved.

**Comment by zijistark** [comment]
10% MA boost is 1/3 the way to reforming a pagan religion and twice the bonus for deposing an antipope.  5%?

**Comment by zijistark** [comment]
I mean, 10% MA is the same as controlling 2 holy sites.

**Comment by thefinestsieve** [comment]
I'm going with 5% for now. It's also funny you should mention that, because in the thread @Jorlem linked above he modified the Blot to give Germanics 10% MA for sacrificing the head of a holy order. If they end up integrating the mod he built, I wouldn't be shocked if there's a 20% MA bonus for sacrificing the head of a religion.

**Comment by thefinestsieve** [comment]
Update: This is part of the in-progress Crier module. The moment it gets into beta, I'll be closing this issue.

**Comment by zijistark** [comment]
And Crier was released.  Closing this issue now. [ Also testing GitHub service integration with Slack. ]
