### ISSUE TITLE
Mongol Invasion Rework!

### ISSUE THREAD

**Issue by dangitsdaaaaang** [zijistark/EMF#467]
At the moment, the Mongol invasion stands to be improved in terms of land distribution and historical outcomes. Goal of rework is to:
- mimic distribution of Mongol rulers to what would more or less be their historical domains (ie no Mongol governors in Russia, Mongol direct control over most of Persia)
- Give Genghis' sons clan titles that correspond to their descendants' successor states to make sure all of them get a piece of the pie, instead of randomly generated khans taking control

CB Editing:
- Make use of the three zones of Mongol conquest: annexation, domination, and subjugation.
- In annexation territories, the majority, if not all, land should end up under Mongol control
- In domination territories, the capitals of the conquered lands will be under direct Mongol control, but a significant number of the native ruling class should remain
- In subjugation territories, the conquered should only have to swear an oath of fealty upon conquest. No lands should be lost.

**HISTORICAL**
- edit sons' histories so that they are each born with their own dynasties, making their existence as nomadic clans later on possible. Edit all relatives of Genghis that are descended from these sons to their appropriate dynasties (Chagatayid, Jochid, Toluid)
- create three clan titles for Chagatai, Jochi, and Tolui corresponding to the Chagatai Khanate, Golden Horde, and Ilkhanate, respectively. Use the flags of e_chagatai, e_golden_horde, and e_il-khanate for ease. Ogedei does not get a clan as his house will be that of the Great Khan up until the breakup of the unified Empire, so it makes sense for him to remain Borjigin.
- Edit histories from 1218-1227 so that each son gains lands as the Empire expands. Chagatai will at first gain the counties of Yedisu and Bulusughnan (Gobalik) and then most of East Turkestan with the exception of Ayaguz. Jochi will gain the eastern half of West Turkestan starting from Jand in 1219, and Tolui will gain most of Daylam, Khoarasan, and northern Persia starting with Otrar in 1219. Use the 1227 BM as a reference for what lands each would have when Genghis dies.
- Look into why the Mongols event does not fire properly in the 1212 BM.

**AHISTORICAL** (Temujin dies and another Genghis Khan must take his place)
- create an alternate Genghis (code for this already exists) that more or less resembles him and comes with sons. For sake of convenience, sons should have the same names so that the three clan titles in the **Historical** section may be used
- Add a CB success condition that ensures that when there is enough land, the game will automatically hand it out to Genghis' sons and create their clan titles accordingly. These should more or less correspond to the traditional directions of expansion: Jochi into Siberia and Russia, Chagatai into East Turkestan and the Hindu Kush, and Tolui into the Persia. This CB success condition will apply to the 1217 historical bookmark as well, since the Mongols only own three provinces and none of which make sense to be given as grazing grounds to Genghis' sons.

**Comment by zijistark** [comment]
Everything regarding historical clans and the distribution of land to them is obsolete due to @Rylock's mongol split approach (which is more practical, IMHO).

Stuff related to ensuring historical demesne of historical characters is out of scope for EMF and CK2.

The three conquest zones idea, however, may be rolled into my next iteration upon the `emf_mongol_invasion` CB.  I'm not entirely sure how I want to go about this yet, but I consider this issue to be resolved now in the sense that its actionables are either no longer applicable or will be applied in a yet to be determined way in very-near-future plans for rework of how mongol land distribution and conquest works during the invasion phase.
