### ISSUE TITLE
Nomad vassals are no longer a thing

### ISSUE THREAD

**Issue by Ispil** [zijistark/EMF#526]
To quote the new tributary relationships file:

`# Note - Characters set as vassals to nomads who are a different culture will end up this tributary type if Horse Lords is enabled`
`# This is hardcoded`

This, I imagine, breaks lots of things that we do regarding nomads.

**Comment by zijistark** [comment]
I can't think of anything off the top of my head that this would break in EMF, but yeah, I'm sure there's something. Irregularity noted, nothing I can do about it until I see something break, so closing issue.
