### ISSUE TITLE
Non-existent event picture references

### ISSUE THREAD

**Issue by zijistark** [zijistark/EMF#530]
... for each, either a different event picture needs to be used or a tweak to the defined event pictures needs to be made. It's possible that the aztec ones are a false positive -- might have had SI disabled for this run.
- [ ] Non-existent image for event picture 'GFX_evt_council_muslim'. meneth.401
- [ ] Non-existent image for event picture 'GFX_evt_juggler'. 91206
- [ ] Non-existent image for event picture 'GFX_evt_temple'. emf_holdings.1402
- [ ] Non-existent image for event picture 'GFX_evt_temple'. emf_holdings.1414
- [ ] Non-existent image for event picture 'GFX_evt_temple'. emf_holdings.1426
- [ ] Non-existent image for event picture 'GFX_evt_apocalypto'. emf_nwo.1
- [ ] Non-existent image for event picture 'GFX_evt_joust_muslim'. emf_tournament.252
- [ ] Non-existent image for event picture 'GFX_evt_throne_room_mesoamerican'. TOG.403
- [ ] Non-existent image for event picture 'GFX_evt_bishop_jain'. RoI.210
- [ ] Non-existent image for event picture 'GFX_evt_bishop_aztec'. SoA.2509
- [ ] Non-existent image for event picture 'GFX_evt_throne_room_mesoamerican'. SoA.2531
- [ ] Non-existent image for event picture 'GFX_evt_aztec_explorers'. SoA.3081
- [ ] Non-existent image for event picture 'GFX_evt_throne_room_mesoamerican'. SoA.3082
- [ ] Non-existent image for event picture 'GFX_evt_throne_room_mesoamerican'. SoA.3083

**Comment by IhateTrains** [comment]
The aztec ones are false positives.

**Comment by zijistark** [comment]
Turns out this issue was outdated. @DelnarErsike restored the event pictures we needed, and we now have no missing event pictures. Closing issue as resolved.
