### ISSUE TITLE
EMF+V `emf_region_mongol_core` is ill-defined

### ISSUE THREAD

**Issue by zijistark** [zijistark/EMF#531]
Relevant errors from an EMF+V run:
- [x] Region 'emf_region_mongol_core' have multiple entries for the province '638'
- [x] Region 'emf_region_mongol_core' have multiple entries for the province '636'
- [x] Region 'emf_region_mongol_core' have multiple entries for the province '639'
- [x] Region 'emf_region_mongol_core' have multiple entries for the province '853'
- [x] Region 'emf_region_mongol_core' have multiple entries for the province '641'
- [x] Region 'emf_region_mongol_core' have multiple entries for the province '640'
- [x] Region 'emf_region_mongol_core' have multiple entries for the province '637'
- [x] Region 'emf_region_mongol_core' have multiple entries for the province '643'
- [x] Region 'emf_region_mongol_core' have multiple entries for the province '645'
- [x] Region 'emf_region_mongol_core' have multiple entries for the province '642'
- [x] Region 'emf_region_mongol_core' have multiple entries for the province '691'
- [x] Region 'emf_region_mongol_core' have multiple entries for the province '644'
- [x] Region 'emf_region_mongol_core' have multiple entries for the province '648'
- [x] Region 'emf_region_mongol_core' have multiple entries for the province '647'
- [x] Region 'emf_region_mongol_core' have multiple entries for the province '656'
- [x] Region 'emf_region_mongol_core' have multiple entries for the province '659'
- [x] Region 'emf_region_mongol_core' have multiple entries for the province '658'
- [x] Region 'emf_region_mongol_core' have multiple entries for the province '663'
- [x] Region 'emf_region_mongol_core' have multiple entries for the province '715'
- [x] Region 'emf_region_mongol_core' have multiple entries for the province '657'
- [x] Region 'emf_region_mongol_core' have multiple entries for the province '646'
- [x] Region 'emf_region_mongol_core' have multiple entries for the province '686'
- [x] Region 'emf_region_mongol_core' have multiple entries for the province '784'
- [x] Region 'emf_region_mongol_core' have multiple entries for the province '1139'
- [x] Region 'emf_region_mongol_core' have multiple entries for the province '1113'
- [x] Region 'emf_region_mongol_core' have multiple entries for the province '1370'
- [x] Region 'emf_region_mongol_core' have multiple entries for the province '894'
- [x] Region 'emf_region_mongol_core' have multiple entries for the province '899'

**Comment by escalonn** [comment]
Aw i don't think it used to complain about that. That's a silly thing to warn about. Alright
