### ISSUE TITLE
emf_region_mongol_core multiple entries (EMF+SWMH)

### ISSUE THREAD

**Issue by Ispil** [zijistark/EMF#532]
[region.cpp:175]: Region 'emf_region_mongol_core' have multiple entries for the province '646'
[region.cpp:175]: Region 'emf_region_mongol_core' have multiple entries for the province '659'
[region.cpp:175]: Region 'emf_region_mongol_core' have multiple entries for the province '658'
[region.cpp:175]: Region 'emf_region_mongol_core' have multiple entries for the province '689'
[region.cpp:175]: Region 'emf_region_mongol_core' have multiple entries for the province '1533'
[region.cpp:175]: Region 'emf_region_mongol_core' have multiple entries for the province '663'
[region.cpp:175]: Region 'emf_region_mongol_core' have multiple entries for the province '664'
[region.cpp:175]: Region 'emf_region_mongol_core' have multiple entries for the province '644'
[region.cpp:175]: Region 'emf_region_mongol_core' have multiple entries for the province '1594'
[region.cpp:175]: Region 'emf_region_mongol_core' have multiple entries for the province '642'
[region.cpp:175]: Region 'emf_region_mongol_core' have multiple entries for the province '643'
[region.cpp:175]: Region 'emf_region_mongol_core' have multiple entries for the province '645'
[region.cpp:175]: Region 'emf_region_mongol_core' have multiple entries for the province '1534'
[region.cpp:175]: Region 'emf_region_mongol_core' have multiple entries for the province '638'
[region.cpp:175]: Region 'emf_region_mongol_core' have multiple entries for the province '639'
[region.cpp:175]: Region 'emf_region_mongol_core' have multiple entries for the province '853'
[region.cpp:175]: Region 'emf_region_mongol_core' have multiple entries for the province '640'
[region.cpp:175]: Region 'emf_region_mongol_core' have multiple entries for the province '641'
[region.cpp:175]: Region 'emf_region_mongol_core' have multiple entries for the province '648'
[region.cpp:175]: Region 'emf_region_mongol_core' have multiple entries for the province '647'
[region.cpp:175]: Region 'emf_region_mongol_core' have multiple entries for the province '299'
[region.cpp:175]: Region 'emf_region_mongol_core' have multiple entries for the province '1348'
[region.cpp:175]: Region 'emf_region_mongol_core' have multiple entries for the province '637'
[region.cpp:175]: Region 'emf_region_mongol_core' have multiple entries for the province '852'
[region.cpp:175]: Region 'emf_region_mongol_core' have multiple entries for the province '1536'
[region.cpp:175]: Region 'emf_region_mongol_core' have multiple entries for the province '854'
[region.cpp:175]: Region 'emf_region_mongol_core' have multiple entries for the province '894'
[region.cpp:175]: Region 'emf_region_mongol_core' have multiple entries for the province '899'
[region.cpp:175]: Region 'emf_region_mongol_core' have multiple entries for the province '1535'

**Comment by escalonn** [comment]
should be fixed
