### ISSUE TITLE
Mongol Empire-splitting code not working

### ISSUE THREAD

**Issue by Ispil** [zijistark/EMF#534]
![image](https://user-images.githubusercontent.com/2822855/33527028-7e1ad37e-d817-11e7-8d34-5ed063b7202f.png)
Going off of this image, when Genghis Khan died, his son inherited the Mongol Horde. The splitting event also gave him the Golden Horde. He retained both titles.

**Comment by zijistark** [comment]
It'd be nice if there were more extensive logging inside that part of rylock's code, but from what I understand, the 3-way empire split can also happen 2 ways. Perhaps the 2nd was gobbled up somehow and received only a tiny portion of the land or something. IDK. Need more information.

**Comment by Ispil** [comment]
Another example:

![image](https://user-images.githubusercontent.com/2822855/33529968-41ab739c-d846-11e7-91bd-44e4abb5d466.png)

Something's definitely up.

**Comment by escalonn** [comment]
IIRC the two-way split will happen if there's only two good candidate descendants to hold the titles.
presumably also will happen if there's not enough held land in one of the split regions

**Comment by Ispil** [comment]
I suppose this can be closed, seeing as it has been fixed on the beta branch.
