### ISSUE TITLE
silk_road_trade_post_trigger not updated for EMF+SWMH

### ISSUE THREAD

**Issue by Ispil** [zijistark/EMF#538]
The scripted trigger is in 00_scripted_triggers.txt, which is not uniquely maintained in EMF+SWMH at all. It currently does not match SWMH's silk road provinces. Notable examples include Khwarezm and Bukhara.

**Comment by Ispil** [comment]
Fixed in beta.

**Comment by zijistark** [comment]
Fixed in release, actually.

**Comment by Ispil** [comment]
Oh yeah, that one was fixed earlier.
  Was thinking Hydra3, not Hydra2
