### ISSUE TITLE
Lefthanded trait has screwed up icon and description

### ISSUE THREAD

**Issue by zijistark** [zijistark/EMF#558]
![image](https://user-images.githubusercontent.com/6268890/52179871-5cf95d00-2794-11e9-9993-b5ce3e2d1836.png)

**Comment by DelnarErsike** [comment]
Possibly a duplicate of #565?

**Comment by zijistark** [comment]
Very likely, although I didn't get a `version.txt` for this guy, so I can't be sure SED is involved, as is the current hypothesis there.

**Comment by zijistark** [comment]
Nevermind, heh.  Looking at the screenshot, SED is definitely involved. Leaving open in any case as there doesn't seem to be a way to merge an issue into another.

**Comment by escalonn** [comment]
fixed
