### ISSUE TITLE
[CPRplus issue] Arpad given Saint background inappropriately.

### ISSUE THREAD

**Issue by zijistark** [zijistark/EMF#560]
User says:
> Arpad is living and Tengri yet has a saint's background. First bug of the day.
> reproduction, ehh
> it showed up when i had him commanding my left flank
> after crossing the carpathians this happened
> i expected him to keep the eagle warrior's headdress that he had before

@dangitsdaaaaang says:
Regarding the Saint background one, I think it happens with Arpad when leading troops on plains.

![image](https://user-images.githubusercontent.com/6268890/52180030-f9702f00-2795-11e9-9f99-5d376bd9815c.png)

@ese-khan I had trouble accessing your new CPRplus repo via the web, or I would've posted there.

**Comment by ese-khan** [comment]
Fixed.
