### ISSUE TITLE
[CPRplus] Urzhailian portrait sets are still in the files and being utilized by random world generation.

### ISSUE THREAD

**Issue by zijistark** [zijistark/EMF#563]
User says:

> It was expressed to me previously that these were thought to have been removed, so this is likely to be considered an issue. Aesthetically, it also does not fall in line with the other portrait sets as seen in CPR+.

![image](https://user-images.githubusercontent.com/6268890/52180117-0e00f700-2797-11e9-9dee-54362c7159c6.png)

Pinging @ese-khan on this one.

**Comment by ese-khan** [comment]
Fixed - or rather, the portrait removed.
