### ISSUE TITLE
Some traits have no localisation.

### ISSUE THREAD

**Issue by zijistark** [zijistark/EMF#565]
Version (notice that SED is installed, may be related @escalonn though the missing trait gfx couldn't be SED):
> [HIP Release [DEV: 2019-02-03 01:07]]
> EMF: Extended Mechanics & Flavor (v9.0-BETA - 2019-02-02)
> Arumba and Internal Tab Shortcuts (2019-01-15)
> ARKO Interface (2018-06-16)
> SWMH (v3.2-BETA - 2019-02-01)
> MiniSWMH: Performance-Friendly SWMH (v1.4-BETA - 2019-01-30)
> SED: English Localisation for SWMH (v2.2.19 - 2019-02-03)
> ARKO Armoiries (2018-06-16)
> LTM (C - 2017-12-09)
> CPRplus (v3.0.1 - 2019-01-02)

Says:
> I got the Strong Basileus trait as intended, however the actual trait doesnt appear to have a proper name or description. Same thing happened with the perceptive trait, which doesnt have a proper name or description.

![image](https://user-images.githubusercontent.com/6268890/52180195-20c7fb80-2798-11e9-9f5b-850dd4d07d4f.png)

![image](https://user-images.githubusercontent.com/6268890/52180198-2887a000-2798-11e9-9f1f-5f9836e2c477.png)

**Comment by zijistark** [comment]
Update: The *icons* for these 2 traits are indeed actually showing.  It's just the localisation, which makes me think SED.

**Comment by zijistark** [comment]
Another user without SED appears to not be having the problem:

![image](https://user-images.githubusercontent.com/6268890/52180231-887e4680-2798-11e9-9fa2-52ec9fe7e96a.png)

User was running EMF+SWMH still. This must be a SED issue @escalonn.

**Comment by escalonn** [comment]
fixed
