### ISSUE TITLE
Autolander should check gender laws when filtering `best_fit_character_for_title` for stupidity.

### ISSUE THREAD

**Issue by zijistark** [zijistark/EMF#567]
User says:
> in "grant recently acquired land" decision there is option to give land to my wife, whitch should be impossible because i cant do it manually

![image](https://user-images.githubusercontent.com/6268890/52181943-9fc72f00-27ac-11e9-8aa5-eb6df150af33.png)

**Comment by DelnarErsike** [comment]
Why exactly wouldn't the character be able to grant the title to their wife outside of the event?

**Comment by zijistark** [comment]
He doesn't have Absolute Cognatic Succession (or Enatic or Enatic-Cognatic), so he can't grant a landed title to a woman directly.
