### ISSUE TITLE
Double Magyar bloodlines founded in an 867 game.

### ISSUE THREAD

**Issue by zijistark** [zijistark/EMF#571]
One on 867.1.1 (must be scripted) and then one by another Arpad in 871:

![image](https://user-images.githubusercontent.com/6268890/52231308-6f47c980-286e-11e9-8215-fb8e6b4bda66.png)

**Comment by zijistark** [comment]
[HIP Release 2019-02-03 (Furry1 Beta2)]
EMF: Extended Mechanics & Flavor (v9.0-BETA - 2019-02-02)
Arumba and Internal Tab Shortcuts (2019-01-15)
SWMH (v3.2-BETA - 2019-02-01)
ARKO Armoiries (2019-02-03)
LTM (C - 2012-02-03)
CPRplus (v3.0.1 - 2019-01-02)

**Comment by ese-khan** [comment]
Ah, base SWMH gives the Arpad bloodline AFTER 867, whereas E+S does so in 867 - so which one's right?

**Comment by ese-khan** [comment]
In fact, wouldn't be more appropriate to give the Arpad bloodline AFTER the migration event chain? Once the conquest is done?"

**Comment by zijistark** [comment]
No clue other than only one of 'em.  Given the description of the bloodline, it seems better to have it slightly after 867 start so that Almos Arpad doesn't already have the bloodline.  OTOH, I don't think the migration event chain is giving this bloodline currently, so IDK.

**Comment by zijistark** [comment]
I'll see if it's easy for me to add this bloodline dynamically (I fear that code, lol). Unfortunately I've stayed away from all bloodline coding so far, so it may take a bit.

**Comment by ese-khan** [comment]
No, the event chain doesn't currently. That's why I'm suggesting - giving the bloodline seems more appropriate that way, E+V or E+S.

**Comment by ese-khan** [comment]
Just changed the bloodline acquisition date to 868 like vanilla, for now.
