### ISSUE TITLE
HF coronation must be taught that vassal kings with an EMF imperial government form shouldn't be crowned.

### ISSUE THREAD

**Issue by zijistark** [zijistark/EMF#597]
This may require an audit of everywhere the HF coronation system checks for a valid coronation candidate. Most of everything should already be covered by the scripted triggers `emf_needs_coronation` or `emf_uses_furry_coronation`, however.

**Comment by DelnarErsike** [comment]
How would this interact with the opinion malus for having an uncrowned ruler under HF coronation? Is there a way to selectively disable it?
