### ISSUE TITLE
Council Laws Rewrite

### ISSUE THREAD

**Issue by DelnarErsike** [zijistark/EMF#624]
Council laws are currently both all over the place power-wise (e.g. execution council voting power is nowhere near as powerful as something like title revocation council voting power) and often don't cover certain actions that they should (e.g. title revocation council voting power does not cover the decision to revoke a lollard temple holding from an appropriate target, execution council voting power does not cover Kharijite public executions).

I propose consolidating the currently 7 council power laws into 4 along the lines of how they are in AGOT mod: Law voting power, Diplomacy voting power, Titles voting power, and Justice voting power.

- Law voting power remains almost unchanged compared to vanilla, The only changes are that its Ruler option now grants +1 demesne size instead of +2 (with the other +1 being moved to Imperial Administration law) and now also grants -5 vassal limit.
- Diplomacy voting power is an expanded version of the old War voting power. Other than declaring wars, Diplomacy voting power also controls voting over NAPs, alliances, prepared invasions, asking to join wars, dissolve tributary relations, asking for vassalization, offering vassalization, and releasing vassals. Its Council option also now gives +5 vassal limit instead of +2 and is no longer a requirement for other council laws to be set to the Council option (though it still prevents councilors from joining factions).
- Titles voting power is a consolidated and expanded version of Title Granting and Title Revocation powers. Aside from granting and revoking titles, this law also controls voting over transferring vassals, retracting vassals, absorbing and splitting of nomad clans, and the special Lollard temple revocation decision. Its Council option also gives +5 vassal limit instead of the +4 that its old component laws would have given.
- Justice voting power is a consolidated and expanded version of Imprisonment, Execution, and Banishment powers. Aside from the old powers over imprisonment, exile, and execution, this law also controls voting over ransoming prisoners, releasing prisoners, recruiting prisoners, moving prisoners between house arrest, dungeon, and oubliette, castrating prisoners, blinding prisoners, the Zun judgement decision, and the Kharijite public execution decision. Its Council option also gives +5 vassal limit instead of the +6 that its old component laws would have given.

**Comment by zijistark** [comment]
I like the idea of consolidating the council power laws (and the different bonuses/maluses seem appropriate) as well as actually enforcing them properly on decision-based stuff like the Kharijite public executions.

You do mention some extra hard-coded stuff that's covered by these laws, e.g.:
> this law also controls voting over transferring vassals, retracting vassals, absorbing and splitting of nomad clans,

I know that we can add council voting upon targeted decisions, and I suspect that we can also add it for any hard-coded diplo-interaction (provided we supply the appropriate voting patterns), but I'm not sure of the latter, so I guess I seek confirmation of this.

**Comment by zijistark** [comment]
Nice work! Praise @DelnarErsike! :raised_hands:
