### ISSUE TITLE
Sieges are destroying too many buildings overall. (emf_siege.200 and emf_siege.201)

### ISSUE THREAD

**Issue by zijistark** [zijistark/EMF#631]
User **Piisamirotta** said:
> The siege events emf_siege.200 and .201 seem to fire too often, leading to barren holdings all over the place. The weights probably need to be played around with as the destruction mechanic itself is pretty cool, as it stands many holdings around the map end up entirely without buildings. Zag14 was kind enough to provide some pictures as proof: https://imgur.com/a/SFFvKeV, the user Ferreira seemed to have noticed the issue too on the main download thread. Running latest Furry 1 plus some personal touches which should not effect the frequency of the event firing.

Normally, I'd not pay much attention to this kind of thing -- nature of the RNG and the fact that early start dates generally don't have much of any buildings built from the get-go, but the pictures are more damning, as the year is 1005, which means ~150 years of gameplay have occurred, and we should expect to not see building-less holdings all over the place at that point, so I definitely think the mechanic needs some more calibration:

![image](https://user-images.githubusercontent.com/6268890/52958127-48969200-3348-11e9-86fe-a734687ce339.png)
![image](https://user-images.githubusercontent.com/6268890/52958141-50563680-3348-11e9-8428-262fe4d4e1ae.png)
![image](https://user-images.githubusercontent.com/6268890/52958174-5ea45280-3348-11e9-888a-94d1c2b6426e.png)

**Comment by Ispil** [comment]
Indeed, they do seem to be firing more often than they should. I am curious, though, why this wasn't brought up before- perhaps siege events in general are firing more frequently due to HF? Regardless, it certainly does need tweaking.
