### ISSUE TITLE
Proselytizing hellenic_pagan_reformed cannot use Convert Province ambition.

### ISSUE THREAD

**Issue by zijistark** [zijistark/EMF#644]
Forum user **Victor Tadeu** said:
> Not sure if a bug or not, but I converted to hellenic, I even reformed the religon and choose Proselytizing, but the Convert Province Religion ambition doesn't show at all.

Likely the pagan group is excluded from the ambition, but we should also perhaps take into account whether a reformed pagan faith has the Proselytizing doctrine.

**Comment by DelnarErsike** [comment]
I suspect it's something else. Here's the allow block for the ambition to convert a province:
```
allow = {
	is_playable = yes
	is_adult = yes
	prisoner = no
	is_incapable = no
	NOT = { trait = cynical }
	piety = 0
	OR = {
		AND = {
			ai = no
			any_realm_province = {
				NOT = { religion = ROOT }
			}
		}
		any_demesne_province = {
			NOT = { religion = ROOT }
		}
	}
}
```
There's nothing there filtering out what religions can and cannot use it, so I suspect the user either had negative piety or had Cynical.
