### ISSUE TITLE
When wife becomes pregnant, event calls her a concubine

### ISSUE THREAD

**Issue by zijistark** [zijistark/EMF#647]
> When my wife becomes pregnant I get the event for the pregnant concubine, it doesn't seem to be an issue with the localisation, it's the 413 event according to the debug tips. The children are born normally, without the child of concubine trait.

```
[HIP Release 2019-05-18 (Furry7)]
EMF: Extended Mechanics & Flavor (v9.06 - 2019-05-18)
Arumba and Internal Tab Shortcuts (2019-05-18)
SWMH (v3.26 - 2019-05-17)
ARKO Armoiries (2019-05-17)
LTM (C - 2019-05-17)
```

![image](https://user-images.githubusercontent.com/6268890/58017783-eae42400-7ab5-11e9-9030-0ed88db0fab9.png)

**Comment by DelnarErsike** [comment]
The plot thickens: you should have gotten event id 403, not 413. 413 is exclusively for consorts, whereas 403 is for wives.

**Comment by zijistark** [comment]
Maybe this is a bug that comes from the changes to the meaning of the consort-related triggers in patch 3.0?  I feel like we'd be seeing this more often since then, though -- rather than roughly since 3.1.1.
