### ISSUE TITLE
[SWMH] Silk road aesthetic path adjustment

### ISSUE THREAD

**Issue by zijistark** [zijistark/EMF#648]
Suggested on Discord by the author of the Expanded Trade submod:

> This portion of the silk road looks like ass now, probably because the 1942 sea province was adjusted:

![image](https://user-images.githubusercontent.com/6268890/58092257-7c1fcd00-7b80-11e9-9e48-b1a9b20767cf.png)

> I suggest you just use my version, which looks like this:

![image](https://user-images.githubusercontent.com/6268890/58092272-8b067f80-7b80-11e9-9621-eafcb09e3ca4.png)

> So "... 1844 1944 1552 1943 ... " instead of the HIP version, which is "... 1844 1944 1942 1552 1943 ..."

( Suggested path simply excludes the extraneous seazone 1942 )

**Comment by ese-khan** [comment]
Looks like the recent brouhaha with the `positions.txt` fixes somehow changed the naval position of the Coast of Somalia. We can just revert the position to the old and be done with it. Or just bypass Socotra altogether, which I'm not averse to :p

**Comment by zijistark** [comment]
The port was likely moved to point into the Coast of Yemen seazone, probably yes. However, I didn't move ports for no reason -- it was to put them in reasonable / workable positions such that they don't conflict with a wonder position.

Why don't we just go with the suggested change, to exclude the Coast of Somalia seazone? It looks perfect, the change has no gameplay difference whatsoever, the change is easy AF to make, etc.

**Comment by zijistark** [comment]
Also, to note: I'd be totally opposed to bypassing Socotra on the Spice Route.

**Comment by zijistark** [comment]
EDIT:
When I said:

> Why don't we just go with the suggested change, to exclude the Coast of Yemen seazone?

I meant:
Why don't we just go with the suggested change, to exclude the **Coast of Somalia** seazone?

**Comment by ese-khan** [comment]
So long as skipping a seazone is fine, I'm fine with that. I think it is.

Any reason for opposing bypassing Socotra? From a historical standpoint IMO Silk Road extension there makes the island worthier than it was. Contemporary records make little to no mention of marketable resources. There were trades between Socotra and the outside, of course, but there are countless examples of that.

**Comment by zijistark** [comment]
Purely from a gameplay perspective, it's just fun having Socotra be on the Spice Route / Southern Silk Road, and since the island is literally right in the way of the route, it just seems weird not to include it, frankly.

Unless the island was something like the islands of the Canarias were -- inhabited by aboriginals that most definitely did not partake in trade with the outside world -- then I don't see any reason to exclude it. It can make a fun start -- or at least make the prospect of playing on Socotra a lot more interesting, and I've seen players do just that with this exact reasoning.

**Comment by zijistark** [comment]
As far as skipping seazones, yeah, I'm almost positive that is no issue whatsoever.  Ultimately I think all the seazones on any of the trade route paths (i.e., generically, the game mechanic itself) are for decoration.  The trade route system only cares about sieged or occupied provinces on the path for the purposes of determining wealth bonus along the route (downstream of the sieges/occupations), and you cannot siege or occupy a seazone.

**Comment by KingofCool** [comment]
It was mainly for gameplay reasons that i added it to the route back in the day. Socotra's place on the route were my doing.

**Comment by KingofCool** [comment]
Personally i think it's a nice little bit of flavour to an otherwise flavour thin corner of the map

**Comment by zijistark** [comment]
Made the change as suggested. Closing issue.
