### ISSUE TITLE
Update EMF+SWMH bookmarks & finalize them.

### ISSUE THREAD

**Issue by zijistark** [zijistark/EMF#671]
EMF+SWMH bookmarks, selectable characters, and text descriptions for 993-1018 and 936 need to be finalized. Make sure that SED is not overriding the bookmark title text or description text as null, as that was the case less than a week or so ago when I was messing around with 993.

**Comment by ese-khan** [comment]
I don't have any unrealized bookmarks, but I'd like to visit the 993 and 1000 bookmarks.

- 993 (Age of Kings): would like to replace Georgios Tzul with a recently-crowned king (like Hughes Capet), usurper (Didda in Kashmir), or a real power behind the throne (Almanzor in al-Andalus).
- 1000 (A New Millennium): a wider range of characters besides the two figures mentioned (Stephen of Hungary and Mahmud Ghazni), I suppose.

**Comment by zijistark** [comment]
Looks like you haven't made those modifications yet @ese-khan. You're clear to do so if you want, else I should close this issue as complete.

**Comment by ese-khan** [comment]
Anyone is welcomed to make edits, from now, of course.
